### ISSUE TITLE
리드미 작성 양식을 고민해봅시다

### ISSUE THREAD

**Issue by jiheon788** [Wanted-PreOnboarding-Team-8/wanted-pre-onboarding-frontend-1#14]
## 주제
[과제 피드백](https://www.notion.so/1-2-30e0e3bfca3544b3aaffe51fd8df2405?pvs=4)을 보시면 리드미에 대한 피드백을 볼 수 있습니다. 좋은 리드미를 작성하기 위해 넣을 내용을 고민하면 좋을것 같습니다. 제가 생각한 내용은 아래와 같습니다. 추가 아이디어가 있으시면 말씀해주세요.🙇🏻‍♂️

---
####  필수 내용
- 제목, 소개 글
- 배포링크, 기능 구현 목록 링크
- 기능
- 기술 스택
- Getting Started
- Demo
- 과제 진행 방법
  - 어떻게 동료 학습/협업을 하였는지 설명 (작업 프로세스 개요??)
  - 분기별 베스트 프렉티스/추가사항 그리고 선정한 이유/추가한 이유 + 각 PR링크

**Comment by jhoon9494** [comment]
폴더 구조랑 혹시 나중에 발생할 수 있는 트러블 슈팅에 대한 것도 적으면 좋을 것 같습니다.

**Comment by jiheon788** [comment]
> 폴더 구조랑 혹시 나중에 발생할 수 있는 트러블 슈팅에 대한 것도 적으면 좋을 것 같습니다.

@jhoon9494 좋은 생각이네요! 초기에 path alias 에러난 것들도 적을 수 있겠네요. 감사합니다

**Comment by jiheon788** [comment]
+ 팀원목록

**Comment by greyHairChooseLife** [comment]
설계도 들어가면 좋을 것 같습니다. 과제에 따라 적절한 형식으로요.  폴더구조에 같이 들어가면 좋을 듯 합니다.

배포링크, 기능 구현 목록 링크, Demo  요놈들은 한 섹션에 넣어도 충분할 것 같습니다.

실행 환경 넣어주면 좋겠습니다.

개인적으로는 마지막에 '과제 진행'으로 묶으신 내용이 제일 중요할 것 같습니다. git flow도 도식으로 넣어주면 좋을 것 같아요.

**Comment by jhoon9494** [comment]
> 실행 환경 넣어주면 좋겠습니다.

@greyHairChooseLife 실행 환경에 패키지 목록도 같이 넣어주면 어떨까요?

**Comment by bokjunwoo** [comment]
과제 진행하면서 이슈에 대한 해결방안도 적어보면 좋을거 같습니다.
