### ISSUE TITLE
소문자로 이름 지어진 상수가 있는 것 같습니다.

### ISSUE THREAD

**Issue by greyHairChooseLife** [Wanted-PreOnboarding-Team-8/wanted-pre-onboarding-frontend-1#20]
/src/api/apiClient.ts

line : 10     const host = 'https://pre-onboarding-selection-task.shop';

이것도 상수인 것 같은데 대문자로 바꾸는 게 맞을까요 아니면 constant에 가야 할까요?

혹은 어떤 다른 이유가 있는걸까요?

**Comment by jiheon788** [comment]
보통 서버 주소는 .env에 넣어서 사용하는데 공개 주소라 그냥 적었습니다! 만약 바꾼다면 상수보다는 env 파일 만드는게 좋을거같네요. 내일 다른 분들 의견도 들어보고 정해봐요

- 루트 경로/.env
```
REACT_APP_SERVER_URL={server url}
```
