### ISSUE TITLE
1. 타입 선언만 있는 파일 이름을 .d.ts로 정하면 좋을 것 같습니다.

### ISSUE THREAD

**Issue by greyHairChooseLife** [Wanted-PreOnboarding-Team-8/wanted-pre-onboarding-frontend-1#30]
근거 1. .tsx 와 .ts로 구분하는 것 보다 눈에 잘 띄고 명확합니다.

  근거 2. tsc 컴파일 결과로 만들어지는 .d.ts파일과 직접 만든 .d.ts파일이 구분되어야 할 이유가 없는 것 같습니다.

  근거 3. 관련 검색 결과 
  
    <== 요약 [ .d.ts 쓰되 이름은 알아보기 좋은 걸로 적당히 지어라 ]

    <== For filenames that contain type definitions or interfaces in TypeScript, the convention is to use a .d.ts extension. This extension indicates that the file contains only declarations, without any executable code.

    For example, if you have a file that contains some interface and type definitions for your application, you could name it as follows:

    perl
    Copy code
    my-interfaces.d.ts
    In this example, the filename is "my-interfaces.d.ts", which follows the convention of using PascalCase for the filename and adding the .d.ts extension to indicate that it contains only declarations.

    It's worth noting that you can use any filename you like for your type definition files, as long as they follow the .d.ts convention to indicate that they contain only declarations. However, using a descriptive filename that reflects the contents of the file can make it easier to understand the purpose of the file, especially when working with larger projects.

    ==> 위 지문에 나온 것 처럼 적당한 이름에 PascalCase.d.ts 어떨까요?

**Comment by jiheon788** [comment]
관련 검색 결과 링크도 부탁드립니다🙇🏻‍♂️

**Comment by hyorimcho** [comment]
회의를 통해 위와 같이 사용하기로 결정했습니다
