### ISSUE TITLE
interface, type 요놈들도 이름 컨벤션이 필요할 것 같습니다.

### ISSUE THREAD

**Issue by greyHairChooseLife** [Wanted-PreOnboarding-Team-8/wanted-pre-onboarding-frontend-1#31]
1. type과 interface를 구분 할 수 있으면서,
  2. 타입 또는 interface인지 아니면 그냥 객체가 할당된 함수인지 확인 할 수 있으면 좋을 것 같습니다.
  3. 더불어 차차 의미상 어떻게 나눌지도 정하면 좋겠습니다. 이것은 정답이 있는건 아니라고 알고있습니다.

  현재는 오락가락 합니다. 
  
  경우 1. I***
  경우 2. ***Type
  
  api/todo/types.ts:1:                       export interface createTodoType {
  api/auth/types.ts:1:                       export interface postSignType {
  lib/hooks/useValidation.tsx:4:                    interface ISignForm {
  lib/routerMeta.ts:1:                       export interface IRouterMeta {
  pages/TodoPage/types.ts:3:                 export interface ITodo {
  pages/TodoPage/types.ts:10:                export interface ITodoForm {
  components/HOC/ProtectedRoute.tsx:6:              interface IProtectedRoute {

**Comment by jhoon9494** [comment]
type으로 선언된 것은 ***Type, Interface로 선언된 것은 I***로 통일하는게 어떨까요?
아니면 type과 interface를 모두 하나로 통일하는 것이 좋을까요?

**Comment by tnghgks** [comment]
저도 Type, Interface 모두 사용되기 때문에 정훈님 말씀대로 컨벤션을 정하는게 좋은 것 같습니다.

**Comment by hyorimcho** [comment]
Interface 는 `I***` 로 Type `***Type`로 통일하여 사용하기로 결정하였습니다.
의미상 어떻게 나눌지는 좀 더 논의해보아요!
