### ISSUE TITLE
router 폴더가 필요 할 것 같습니다.

### ISSUE THREAD

**Issue by greyHairChooseLife** [Wanted-PreOnboarding-Team-8/wanted-pre-onboarding-frontend-1#32]
routerMeta 파일은 라우터에서만 사용하는 타입 파일입니다. 그런데 갈 곳을 잃고 lib/ 에서 헤메고 있는 것 처럼 보입니다. 아니면 어떤 이유가 있을까요?
  
  router폴더 안에 routerMeta.d.ts 또는 router-meta.d.ts 좋을 것 같습니다.

**Comment by jhoon9494** [comment]
좋은 것 같습니다! 다만 d.ts 형태로 붙일 이유가 따로 있는지 궁금합니다!

**Comment by hyorimcho** [comment]
다음부터는 만드는 것으로 하겠습니다 😀
