### ISSUE TITLE
 npx 명령어 사용 한 번 하는 것으로 .prettierignore 파일을 삭제 할 수 있습니다.

### ISSUE THREAD

**Issue by greyHairChooseLife** [Wanted-PreOnboarding-Team-8/wanted-pre-onboarding-frontend-1#33]
(번복 죄송합니다. 머리가 빨리 빨리 안돌아갔습니다.)
  
  저희 프로젝트 root 경로에서,

  npx prettier --write .
  npx eslint --fix .
  
  이렇게 한번 진행 해 주시면 좋을 것 같습니다. 참고로 npx는 npm으로 설치하여 사용하는 패키지들을 로컬에 설치하지 않고 최신버전으로 실행 만 하는 명령어입니다.

  일부 팀원(지금은 저 한명 뿐이긴 하지만) 때문에 꼭 필요하지도 않은 파일을 모두가 가지고 있어야 한다는 것은 썩 좋은 일은 아닌 것 같습니다. 게다가 그 문제가
  npx 명령 두 번으로 해결된다면 더욱 그런 것 같습니다.

  이미 해결 된 문제지만 쫌 죄송하기도 하고, 어쩄든 더 좋은 방법인 것 같아 제안을 드려 봅니다.

**Comment by tnghgks** [comment]
앞으로 혹시라도 root에 파일이 추가될 수 있는데 추가될때마다 . `.prettierignore`파일을 수정하는것도 효율적이지 않다고 생각이되고, 두번째 방법으로 npx를 활용해 `npx prettier --write .` 등을 실행하는것도 pr 하는사람의 실수로 두번 일하는 일이 생길 수 있다고 생각이되서 조금 찾아봤는데요.

.prettierignore 파일에서 root에서 모든 파일을 예외처리하고 src만 검사하게 하는 설정을 사용하면 어떨까요? 간단하게 다음 두줄만 추가해서 적용할 수 있습니다.

>`.prettierignore`
>```
>/*
>!/src
>```

**Comment by hyorimcho** [comment]
호수님 말씀대로 보일러 플레이트 업데이트 하는 것으로 하겠습니다😀
