### ISSUE TITLE
 organization merge 승인을 위해 모두(또는 과반)의 동의가 필요하면 좋을 것 같습니다. 

### ISSUE THREAD

**Issue by greyHairChooseLife** [Wanted-PreOnboarding-Team-8/wanted-pre-onboarding-frontend-1#34]
근거 1. 팀장님이 아니시더라도 한 명 뿐이라면 예상 밖의 상황에 빠르게 대응하기 어렵습니다.
  근거 2. 인원이 많고, 시간이 짧고, 협업 경험도 적은 많큼 회의에서 모든 내용이 다 합의가 된다고 보기 어렵습니다. 차근차근 보다보면 다른 좋은 의견이나 유익한 비판이 나올 수 있을 것 같습니다.
          저같은 경우는 화면 공유로 설명 해 주시는 것들을 한번에 다 이해하기가 쉽지 않더라고요. 커밋 기록 보면서 차근차근 보면 나름 잘 이해가 되는데 말입니다.
  근거 3. (근거 2에 이어서) 따라서 pull request의 리뷰 기능과 다수 동의에 의한 merge 확정이 기능적으로나 (협업)체계로 보거나 좋다고 생각합니다.

  한편, 앞으로 익숙 해 질 수록 모두 모여서 하는 회의 보다도 시간적으로도 더 효과적일 수 있을 것 같습니다. 시간을 딱 정해두고 리뷰를 마치는(동의/비동의) 식으로 한다던가 하면 말입니다.

**Comment by bokjunwoo** [comment]
팀원들이 모두(또는 과반)의 동의를 해 기록을 남기는 것이 좋아보입니다.

**Comment by hyorimcho** [comment]
좋은 의견이네요 상연님😀!

회의 시간에 코드 리뷰를 하고 투표를 해서 과반수의 동의를 얻은 분께서 best practice가 되는 것이 이미 3번의 역할을 하고 있다고 생각하는데 아닐까요?
다만 지금은 `merge` 버튼을 누르는 권한이 저에게만 있기 때문에 이것은 모두가 나눠가지면 좋다고 저도 생각합니다!

이번 프로젝트는 이미 완성했던 과제를 토대로 진행했던 프로젝트였음에도 인원수가 많다 보니 각자의 코드를 설명하는 데에만 1시간씩이 넘게 소요되었습니다. 다음 기업 과제에서는 더욱 시간이 촉박할 텐데, PR 올리는 시간만 정하는 것보다도 PR 시간을 정하고 리뷰할 시간도 정해서 ( 코드에 코멘트를 남기는 식으로 하면 좋겠죠? ) 그 리뷰를 토대로 회의를 가진다면 더욱 효율적인 회의가 되지 않을까 생각이 듭니다.

**Comment by hyorimcho** [comment]
PR 시간을 정하고 리뷰할 시간도 정해서 그 리뷰를 토대로 회의를 진행해보도록 하겠습니다😎 + 다른 분들이 알아보기 쉽게 커밋 메세지를 정성들여 쓰도록 합시다😀
